### ISSUE TITLE
一个典型的失败 issue 的示范

### ISSUE THREAD

**Issue by MCR-LTS** [biliob233/biliob233.github.io#2]
所有数据有关的功能和观测记录已经崩了快两个星期了，是我知道这里以来最长的一次。
如果你们可以看到，希望你们可以加一纸公告解释一下。毕竟，这应该是唯一全免费的 bilibili 数据站点。对于一个想观测数据的普通白嫖用户，ob 的消失将是毁灭性的。
祝你们好运。

**Comment by MCR-LTS** [comment]
你们要是真的不干了，服务器电线一拔万事大吉，别把整个页面弄的半死不活，让无限的加载磨练我们的意志，在此感谢你们，虽然我百分之百肯定你们已经忘了这个 github 仓库了

**Comment by MCR-LTS** [comment]
我关的不是 issue，而是希望

**Comment by LiO6sunset** [comment]
祝你们国庆快乐吧

**Comment by MCR-LTS** [comment]
又是一个月。一切还是那么寒酸。民主离白嫖群众越来越远。一群冷血动物。

**Comment by MCR-LTS** [comment]
其他类型的东西，作者跑路以后还能用，而你这一跑路是直接功能全废，等同于一个人退网以后顺便销号。
我非常佩服你财力的雄厚，能在这个网站名存实亡之时依然不关闭服务器，在那里肆意挥霍钱财，相当于一个全都把钱投到屁用没有的地方的“顺其自然”。
我也非常好奇你是如何做到有这么强技术能力的同时还保持着如此的“沉默”（这份沉默是痛苦的）。没有人会再知道如何搭建一个 ob ，星星之火传到你这直接拿灭火器一把扑灭了。
现在也许只有两种可能了。一种是你正在忙于学业（但也不至于忙到连发个通知都没空的地步），另一种是我越来越相信的，也是我最不希望发生的——你已经死了。
你在能力上确实水平没的说，但你在情感与沟通方面连个 github bot 都不如。
B 站再无民主，观众也再无民主的自由。我爱你（和谐）。

**Comment by Jannchie** [comment]
> 其他类型的东西，作者跑路以后还能用，而你这一跑路是直接功能全废，等同于一个人退网以后顺便销号。 我非常佩服你财力的雄厚，能在这个网站名存实亡之时依然不关闭服务器，在那里肆意挥霍钱财，相当于一个全都把钱投到屁用没有的地方的“顺其自然”。 我也非常好奇你是如何做到有这么强技术能力的同时还保持着如此的“沉默”（这份沉默是痛苦的）。没有人会再知道如何搭建一个 ob ，星星之火传到你这直接拿灭火器一把扑灭了。 现在也许只有两种可能了。一种是你正在忙于学业（但也不至于忙到连发个通知都没空的地步），另一种是我越来越相信的，也是我最不希望发生的——你已经死了。 你在能力上确实水平没的说，但你在情感与沟通方面连个 github bot 都不如。 B 站再无民主，观众也再无民主的自由。我爱你（和谐）。

@LiO6sunset 

BiliOB233 的维护者也收到了律师函。经过沟通后，确认不会继续维护了。
据我所知，前端页面挂载在了第三方服务下——这是免费的，所以没有关闭。而比较烧钱的后端服务器已经停止运行了。
感谢您的关注。

**Comment by MCR-LTS** [comment]
我是知道有收到律师函这一可能性的。至于我为什么没写上，是我在一天无聊的时候翻阅了过往的观测记录，找到了一条有较多点赞的评论，意思类似“因为网站没备案所以不会再出事了”。出于我极端匮乏的语言表达能力与想象能力，我只能想到这两种离谱并且非常恶毒的可能性。每一条评论发出，我心里一种“与尸体对话”的思想也越来越强，再过几天可能就会直接上升到问候家人的地步。我万万没想到上一条评论能把原作者直接召唤过来，如果影响到了您的心情，在这里致歉。至于刚才火速开了又关 issue，因为我想进一步讽刺，但我 open 以后页面刷新才看到您的回复。

**Comment by ceiminya** [comment]
可笑，引用tuic开发者的话。

你不看文档不看 issue，留下一句“怎么不能用，什么垃圾软件”
你扫了一眼不知从哪里找来的所谓项目介绍，留下一句“就这？这不就是 XXX 吗？”
你提了一大堆功能需求，过了一段时间没看到你提的需求被实现，留下一句“怎么还没实现？这个软件太垃圾了”
你不知怎么遇到的 bug，不附带 log、config、复现步骤就提了一个 issue，过了一段时间没有被解决，留下一句“这作者脾气大还没有责任心，根本不管项目”
你提了一个 issue，过了一段时间没看到回复，留下一句“这个软件太垃圾了，根本没人维护”
在你们眼里，留下一句话只需要动动手指敲敲键盘，不论发些什么，对你们都不会有什么损失。但是，开源项目的开发者们凭什么要帮你们解决这些问题？任何软件都会存在问题，更何况一个不靠利益运作、纯粹靠兴趣驱动的项目？

我们靠着热情开始并维护着这些项目，而热情是有限的，你们却在无时无刻消耗着这些热情。

现在的互联网，特别是简体中文网络上，人们连最基本的心平气和、温文尔雅的交流都做不到，更不要说换位思考的能力了。我不建立所谓的“用户群租”就是因为我深知，由庞大的、层次参差不齐的用户群组成的社区，一定是硝烟弥漫的。我所接触到的所谓的“代理娱乐圈”，就连开发者之间也无法做到相互尊重，心平气和地交流，更何况是用户呢？不明原理就把某些东西捧上天或骂到一文不值，这种行为太常见了。

我并不是说其它“圈子”就没有这种情况，也不是只有简体中文用户会做这种事，只是目前简体中文互联网的风气如此，并且很遗憾这个项目的主要受众就是简体中文用户，所以我才会有这样的感受

**Comment by MCR-LTS** [comment]
有点累了，语文又很烂，下面这些读起来可能会有点困难，但这些是我的真情实感。

写这篇issue的时候我的确是把这个开发者的github资料都翻了一遍，确认没有有关为什么继承网站关闭的任何描述（我知道这个继承网站的时候，就已经知道了biliob原项目被发函的前因后果），随后才作出了这样的发言。那时候，我分不清网站的前后端，以为这只是一次简单的服务器崩溃，像以前多次一样，简单一修就能修好。我每一次打开网站，都只有一个上面转着圈的站娘迎接着我，哪怕原开发者简单的说一句“本项目已被关闭”，也不至于造成我当时那样的情绪。我耐心等待了两个月，才终于写下了这段看起来很温和，但实际上杀伤力很大的话。

我理解每个人做每一项事业的不容易，对于每一个怀有热情的人都持着敬畏之心。事实上，我除了那一个 死 字，全文都是心平气和，温文尔雅。能够保持完全友好的交流在今天的社会上越来越难，把自己心里的坏话憋着不说，就已经是对社会一个很大的贡献了。

那时候我才高一，由于我相对内向的性格，我以前几乎从未在互联网上发过言，以及在现实中与人真正的交往。我语文至今只能及格，也算是个书呆子，现在看来，这些非常耻辱，我再一次对见齐的努力表示衷心的感谢，对我伤害到的那些网站继承者感到万分抱歉。我很久以来一直以为只要说话时不吐脏字就是和谐讨论，然而随着我的成长，我意识到这个想法实在是过于单纯。这是我唯一一次，也是最后一次在互联网上胡乱发言。我可能只不过是比别人成长的慢了一点。

我也对如今中文互联网的风气嗤之以鼻，目前能让我做到屏蔽这些戾气的，就是不看评论，不看贴吧NGA等泥沙俱下的网络论坛，有意识的屏蔽各种我不想看到的信息，毕竟我还在十二年寒窗苦读之中，绝大多数人的戾气都发散到了这个社会上，不知道这些对我也没有什么损失。我已经高三了，我不敢知道，二百天以后，我将面临的是怎样的一个社会。

我是一个非常玻璃心的人，有一个我喜欢的作者因为触犯红线被锤了好几次，我曾迷茫了很久；我因为和我所交的第一个朋友吵架，情绪持续低落，国庆节进了医院，目前已经恢复正常，正在吃药；迄今，我的弹幕屏蔽列表已经超过了同步上限，因为我极其不愿意看到“晦气”“出生”等一系列侮辱性词汇。还有很多想法不知道怎么表达。

最后，bilibili在今天的我眼里已经完全是下一个抖音了。一个个的数据观测网站被发函，评论楼层也已经寿终正寝。感谢每一位推动bilibili民主化的人所做出的贡献，感谢每一个曾经想要维护bilibili独特社区氛围的人的努力，祝陈睿的事业继续蒸蒸日上。
